### ISSUE TITLE
Train yolov5s transformar for mix person

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1029]

**Comment by MunPotter** [comment]
![Screenshot from 2022-11-06 10-53-08.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/4903c4b5-dfa1-4eb2-8085-3b1b24a6a420)

**Comment by MunPotter** [comment]
![Screenshot from 2022-11-06 12-25-09.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/1957201c-56c6-4908-8d7a-6d1dd69e5b2f)
