### ISSUE TITLE
Train yolov5s transformar for activity 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1030]

**Comment by MunPotter** [comment]
![Screenshot from 2022-11-06 13-34-49.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/84676407-9a76-47bc-9c3b-e73f2d065d29)

**Comment by MunPotter** [comment]
![Screenshot from 2022-11-06 14-21-42.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/7252de29-90c9-4506-9674-28ab93f5459e)
