### ISSUE TITLE
Planning and assigning task to team

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1041]

**Comment by tonmoyfarhad** [comment]
Imran
1. Sidebar dynamic active links(6 hours)
 2. Multiple role selection design (8 hours)
 3. Dynamic Data integration from mongodb in role creation (8 hours)
 4. Protected routes (user authorization) (8 hours)
 5. Fetch data for user counts(10 hours) 

Rafiq 
- Camera
  - Camera View
    - Edit and delete the camera page [1.5h]
  - Camera Setup
    - Enter Camera Data Page [2h]
  - Camera Setup Flow Design[4h]

- Machine
  - Machine Page layout Design[1.5h]
  - Enter Machine Data Page[1h]
  - Show Machine Informaation[3h]
    - Header Section
      - title
      - 3 Buttons
      - Dropdown button
    - Body
      - Table
      - Table Pagination
  - Machine Profile Create [1h]
  - Machine Setup Flow Design[4h]

Fayeeza
Setup Factory - 
•    Design 1st Flow Structure of Setup Factory Data [8]
•    Design 2nd  Flow Structure of Setup Factory Data [8]
•    Design 3rd  Flow Structure of Setup Factory Data [8]
•    Design Line Information display [1]
•    Design Add button Information display [2]
•    Folder and code restructuring [6]
•    Working on Internship report [2]
