### ISSUE TITLE
Planning to connect master module with dashboard

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1042]

**Comment by tonmoyfarhad** [comment]
Planning for worker count - 8hrs
Planning for system loss - 8hrs

**Comment by tonmoyfarhad** [comment]
[https://app.zenhub.com/files/460831955/d2273ef2-b495-4d0e-adcf-c0e248f21b2a/download](https://app.zenhub.com/files/460831955/d2273ef2-b495-4d0e-adcf-c0e248f21b2a/download)
