### ISSUE TITLE
 Design Add button Information display 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1049]

**Comment by Fayeeza-altersense** [comment]
After Add button in Floor Information display for break time is clicked a new break time display will appear. 
Similarly for entry exit new data can be added when add button for inputting new entry exit clicked. 
![image.png](https://images.zenhubusercontent.com/633bbdb893f7a72d1a488e88/63ec7a7a-ddcb-4fca-849d-257f5606c223)
![image.png](https://images.zenhubusercontent.com/633bbdb893f7a72d1a488e88/5ff81e81-38e9-41ab-bfe7-832c60e5376b)
