### ISSUE TITLE
Multiple role selection design

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1061]

**Comment by imranhAltersense** [comment]
Multiple role selection design (done)
            --> R & D on npm modules
            --> Created a custom dropdown roll selection according to the figma
            --> created a reusable component for multiple dropdown selection
            --> used the reusable component in create role and create user section
            --> refactored existing code to implement the functionality

**Comment by imranhAltersense** [comment]
Multiple role selection design (done)
            --> R & D on npm modules
            --> Created a custom dropdown roll selection according to the figma
            --> created a reusable component for multiple dropdown selection
            --> used the reusable component in create role and create user section
            --> refactored existing code to implement the functionality
