### ISSUE TITLE
Dynamic Data integration from mongodb in role creation 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1062]

**Comment by imranhAltersense** [comment]
There are some issues regarding the task which are:
1. the floor and lines data are dependent on factory selection
2. currently the factory selection is multiple, for this reason the floor name and lines name need to be distinct, as they will be merged and stored in the same mongodb collection
3. Also the plan is changed regarding multiple factory creation (verbal communication between tazaki vai and farhad vai)
4. First we need to fix the plan about the factory creation and if the factory selection will be multiple or single , as we are planning to create different mongodb instance for different factory
5. Once the planning is ready, we can retrieve the data from mongodb and use those data in the role creation
6. Currently, the frontend implementation is ready and it is designed according to the data we are  expecting
7. Planning needs to be done asap

**Comment by imranhAltersense** [comment]
--> Discussion on dynamic data integration of factory, floor and lines
            --> Removed factory (multiple inputs) from ui and refactored the backend
            --> Created a new data schema with farhad vai for floors and lines
            --> Lines inputs are being populated conditionaly depending on selected floors
            --> Edge cases handled(if no floor is selected)
            --> Encountering some issues about  the floor and lines name convention which needs to be fixed
                proposal:
                    1. Both names should be similar in some way(e.g. floor1, floor1Line1 or f1, f1l1)
                    2. We may use id of the floor and depending on the id lines will be displayed (This will take some time as codes need to be refactored and add some functionality but this is prefered)

**Comment by imranhAltersense** [comment]
--> Discussion on dynamic data integration of factory, floor and lines
            --> Removed factory (multiple inputs) from ui and refactored the backend
            --> Created a new data schema with farhad vai for floors and lines
            --> Lines inputs are being populated conditionaly depending on selected floors
            --> Edge cases handled(if no floor is selected)
            --> Encountering some issues about  the floor and lines name convention which needs to be fixed
                proposal:
                    1. Both names should be similar in some way(e.g. floor1, floor1Line1 or f1, f1l1)
                    2. We may use id of the floor and depending on the id lines will be displayed (This will take some time as codes need to be refactored and add some functionality but this is prefered)
