### ISSUE TITLE
Protected routes (user authorization)

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1063]

**Comment by imranhAltersense** [comment]
--> Read documentation and followed some use cases about route protection
            --> Created a function to get the routes and inject the user in the routes to wrap the routes with authorization condition
            --> This functionality needs to be implemented in different routes in order to check if it is working
            --> Create an anauthorized page or redirect to page if route access denied

**Comment by imranhAltersense** [comment]
--> protected routing implemented using svelte spa router documentation
            --> logged in user is passed in the routes and checked the required permission
            --> if required permission is true user can go to that page
            --> unauthorized user can't go to that route, instead they will be redirected to defined route
