### ISSUE TITLE
Server requirement finalization

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#107]
To be done on 28/02/22

**Comment by niyazed** [comment]
- Region: Asia Pacific (Singapore)

|  Instance name | On-Demand hourly rate  | vCPU  | Memory  | Storage  | Network performance |
|---|---|---|---|---|---|
| c5.xlarge  | $0.196  | 4  | 8 GiB  | EBS Only  | Up to 10 Gigabit |   |

**Comment by sabbirkuasha** [comment]
**c5.xlarge**	
4(vCPU)	
8gb(Ram)	
EBS-Only(Instance Storage)	
Up to 10(Network Bandwidth Gbps)	
Up to 4,750(EBS Bandwidth Mbps)
