### ISSUE TITLE
As SA, I want to input section name against auto-generated section ID to create a list of sections along with a check box for if to including line or not.

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1089]

**Comment by rahulxb** [comment]
- [ ] 1. dynamic data with backend (18H)
- [ ]             i. create factory info
- [ ]             ii.  view factory info
- [ ]             ii. edit factory info'
- [ ]         2. progress bar design(4H)
- [ ]         3. progress bar dynamically active(4H)
- [ ]         3. sidebar navigation disabling dynamically(4H)

**Comment by imranhAltersense** [comment]
i. Frontend UI's added(backend will be added later):
            1. create factory info
                --> section add and delete dynamically
                --> code structure changed and code optimized from fayeeza
                --> created necessary routes and conditions
            2. view factory info
            3. edit factory info
        ii. validation added for create factory info page
