### ISSUE TITLE
Working on internship project and report

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1091]

**Comment by Fayeeza-altersense** [comment]
This task will be continued for next week.

**Comment by Fayeeza-altersense** [comment]
- Done new Internship Report in partial fulfillment of the requirement for the Internship Completion certificate.
[https://app.zenhub.com/files/460831955/89890d2f-18b2-49d5-abc9-eb9983918597/download](https://app.zenhub.com/files/460831955/89890d2f-18b2-49d5-abc9-eb9983918597/download)
