### ISSUE TITLE
Create a csv file (Ground Truth) + plot Graphs

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1093]

**Comment by sajidahmed12** [comment]
Generated CSV_file added for ground Truth images. file contains 4 classes. 
Label 0 = no_activity
Label 1 = sewing
label 2 = get_put
Label 3 = anomaly 

link to csv: https://docs.google.com/spreadsheets/d/1iPTcp4hG3V1ZGjn83ndPE0esLgm_nwykjKSPU4vqYxA/edit?usp=sharing

**Comment by sajidahmed12** [comment]
Generated CSV_file added for ground Truth images. file contains 4 classes. 
Label 0 = no_activity
Label 1 = sewing
label 2 = get_put
Label 3 = anomaly 

link to csv: https://docs.google.com/spreadsheets/d/1iPTcp4hG3V1ZGjn83ndPE0esLgm_nwykjKSPU4vqYxA/edit?usp=sharing
