### ISSUE TITLE
Create a csv file (Inference Data)+ plot Graphs

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1095]

**Comment by sajidahmed12** [comment]
Generated CSV_file added for Inference data images (Darknet). file contains 3 classes. 
person, sewing, get_put along with each confidence label and true label besides the confidence.  

link to csv: [person_inf_darknet_csv](https://docs.google.com/spreadsheets/d/1HWH7TH7kVF6EASr5lJvrdGPLJ4PfxyH2PPRVNPnYJ3o/edit?usp=sharing)

[Activity_inf_darknet_csv](https://docs.google.com/spreadsheets/d/1bDxU3Pd0TXtO7q2cpkThEZuhVA1tl9FAs1ouIYQlm24/edit#gid=1474554918)
