### ISSUE TITLE
Compare the results for Inference & Ground Truth 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1097]

**Comment by sajidahmed12** [comment]
Visually Compared the results side by side for a list images.  Also generated some plots for comparison.

**Comment by sajidahmed12** [comment]
![person_ROC.png](https://images.zenhubusercontent.com/63728c3bdd4bacead6dc68b4/84a121ba-18dc-4742-8b0f-d0525b8fcb2a)![Activity_ROC.png](https://images.zenhubusercontent.com/63728c3bdd4bacead6dc68b4/f972d0f6-3124-42f2-81d8-962f89ecf2af)
