### ISSUE TITLE
As SA, I want to see the progress of the multistep forms progress in progressbar, to navigate between next and previous pages and save & exit, also I want to see the sidebars present status

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1117]

**Comment by rahulxb** [comment]
- [ ]  1. creating dynamic progressbar (20H)
- [ ]             --> make sure the already done steps are completed
- [ ]             --> make sure ongoing step is displayed as ongoing
- [ ]             --> make sure the incompleted task is not mark as completed
- [ ]         2. Enabling the functionalities previous, next and save & exit button(15H)
- [ ]             --> previous button should navigate to the previous step(disabled for the first step)
- [ ]             --> save and exit should save save the data and navigate to initial home page
- [ ]             --> next button should navigate to the next step and save the data to db (disabled for the last step)
- [ ]         3. creating dynamic sidebar(15H)
- [ ]             --> make sidebar sync with progress bar
- [ ]             --> make sure the sidebar components are enabled if the corresponding step is completed
- [ ]             --> make sure the sidebar components are disabled if the corresponding step is not completed

**Comment by imranhAltersense** [comment]
#Enabling the functionalities previous, next and save & exit button
            1. created a reusable component for the bottom section(prev, nex and save button)
            2. created stores for related component variables(sidebarstore, editStatusStore)
            3. used context api of svelte to use parent function inside child component
            4. conditionally rendering create, view and edit page based on forms state
            5. conditionally disable save button for view page as it has no functionality of saving data

**Comment by imranhAltersense** [comment]
```
#Enabling the functionalities previous, next and save & exit button (completed)
        --> previous button should navigate to the previous step(disabled for the first step)
        --> save and exit should save save the data and navigate to initial home page
        --> next button should navigate to the next step and save the data to db (disabled for the last step)
        --> save & exit should be disabled for the view page
        --> next button will navigate to the next page only when the form data is saved to db
20.11. 2022
```

**Comment by imranhAltersense** [comment]
```
 # creating dynamic progressbar
        1. stored completed steps in the store 
        2. Ongoing step is displayed as ongoing
        3. updated UI of the multiform steps has been added 
        4. if current step isn't completed, next step can't be accessed
        5. Discussion with teammates about form steps flow and updated functionality
```

**Comment by imranhAltersense** [comment]
# creating dynamic progressbar
        1. make sure the already done steps are completed
        2. store the already completed steps in the database
            i. created collection in meteor sever
            ii. created a method in meteor server to retrive the data(completed steps) from db
            iii. on server startup db populated with initial completed step
            iv. created a function in the store to retrieve the completed steps
            v. created an update method in meteror server to update the completed steps
        3. Conditionally rendered app depending on completed steps are ready or not

**Comment by imranhAltersense** [comment]
# creating dynamic progressbar(completed)
    1. make sure the already done steps are completed
# creating dynamic sidebar(completed)
    1. make sure the sidebar components are enabled if the corresponding step is completed
    2. make sure the sidebar components are disabled if the corresponding step is not completed
    3. created collection, method, store and conditional rendering for sidebar display
