### ISSUE TITLE
 Documentation on what each components is for

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1118]

**Comment by Fayeeza-altersense** [comment]
- A documentation was made to distinguish the old and new UI design and flow 

https://docs.google.com/document/d/1Cq8Hl8WJwkTPi7Wj_QYNTdLS-1libg5sxmr8mVYtOdY/edit?usp=sharing

**Comment by Fayeeza-altersense** [comment]
- A documentation was made to distinguish the old and new UI design and flow 

https://docs.google.com/document/d/1Cq8Hl8WJwkTPi7Wj_QYNTdLS-1libg5sxmr8mVYtOdY/edit?usp=sharing

**Comment by Fayeeza-altersense** [comment]
Additionally done - 
- UML diagram for Setup Factory 
Draw.io link : 
https://drive.google.com/file/d/1EXL5MLGf4lSD2YpSXYCtWTvXS6T-_iXK/view?usp=sharing
