### ISSUE TITLE
Design Machine - Create , View & Edit similar with functionality in Figma [25,26]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1122]

**Comment by Fayeeza-altersense** [comment]
- Create Machine
![Create_machine.png](https://images.zenhubusercontent.com/633bbdb893f7a72d1a488e88/cabd2ccf-1e65-46aa-b370-b43ce9e55923)

- Edit Machine 
![Edit_machine.png](https://images.zenhubusercontent.com/633bbdb893f7a72d1a488e88/85e62b0f-01dc-4be2-84ec-2522e290e2a0)

- View Machine
![View_machine.png](https://images.zenhubusercontent.com/633bbdb893f7a72d1a488e88/b8dd9b45-2428-46eb-b923-86683785bf84)
