### ISSUE TITLE
Yolov5 inference & evaluation for large,small,medium model with prune and quantize model

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1133]

**Comment by MunPotter** [comment]
https://docs.google.com/spreadsheets/d/1B3JZz8O1_BlZEXFh53TNdDNNKicFx0etdFIx2Pn_WmQ/edit?usp=sharing

**Comment by MunPotter** [comment]
https://docs.google.com/document/d/1C5Mn-iLZfdWhiyopKAxyaD42LA-gxLU8xrBvgjEulG4/edit?usp=sharing
