### ISSUE TITLE
Generate Results for test images(by class)

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1142]

**Comment by sajidahmed12** [comment]
Completed ![Screenshot from 2022-11-22 17-54-13.png](https://images.zenhubusercontent.com/63728c3bdd4bacead6dc68b4/9f38d026-e487-4b0d-a86c-9d3e65e91598)

**Comment by sajidahmed12** [comment]
Completed ![Screenshot from 2022-11-22 17-54-13.png](https://images.zenhubusercontent.com/63728c3bdd4bacead6dc68b4/9f38d026-e487-4b0d-a86c-9d3e65e91598)
