### ISSUE TITLE
 Generate CSV & graphs for each classes with Required Infos

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1143]

**Comment by sajidahmed12** [comment]
Generated CSV for both Detection & BBOX_detection. [https://app.zenhub.com/files/460831955/519cd908-b2da-46dd-854e-516d5b1d1e7a/download](https://app.zenhub.com/files/460831955/519cd908-b2da-46dd-854e-516d5b1d1e7a/download)
[https://app.zenhub.com/files/460831955/d64a9379-d36a-4312-89e7-3da0f458dc4f/download](https://app.zenhub.com/files/460831955/d64a9379-d36a-4312-89e7-3da0f458dc4f/download)
