### ISSUE TITLE
Deepsparse test Evaluation for Nabeel Sir

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1147]

**Comment by sajidahmed12** [comment]
1. Completed for one test data (From Cam1 4.11.22 Line 12) data on Model Yolov5_Prune_quantized (DeepSparse) 
2. Will test and evaluate on another batch of data and generate TP, FP, FN and calculate Precision and Recall.,

**Comment by sajidahmed12** [comment]
box num      Multi_person    W           Single   W            Absent    W
- Box 1           167                 3           3333    18             285     283
- Box 2           112                 2            3492    4              171     148
- Box 3           24                   8            656    13              3095    8
- Box 4           112                 15          2876    0               787     221
- Box 5           59                   0            3290    1               426     67

W for Wrong_predictions.

**Comment by sajidahmed12** [comment]
Check task #1133. 

https://docs.google.com/spreadsheets/d/1B3JZz8O1_BlZEXFh53TNdDNNKicFx0etdFIx2Pn_WmQ/edit#gid=2026573946
