### ISSUE TITLE
Develop create Employee section 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1154]

**Comment by rahulxb** [comment]
- [ ] i. create employee
- [ ]             # retrive floor and section from db
- [ ]             # handle frontend user input data
- [ ]             # validation both frontend and backend
- [ ]             # backend method creation and save to db
- [ ]         ii. create designation
- [ ]             # frontend user input data
- [ ]             # validation both frontend and backend
- [ ]             # backend method creation and save to db
- [ ]         iii. conditional rendering of create, view and edit

**Comment by imranhAltersense** [comment]
1. frontend functionality of create employee (completed)
    2. frontend functionaliy of edit employee (completed)
    3. frontend functionality of view employee (completed)
    4. on going
        --> refactoring form bottom component 
        --> redefine edit functionality in store
        --> creating meteor methods in store for reusability

**Comment by imranhAltersense** [comment]
1.create employee (frontend + backend)
    2. view employee (frontend + backend)
    3. create designation (frontend + backend)
    4. view designation (frontend + backend)
    5. Session with rafiq vai
        --> create floor 
        --> view floor 
        --> edit floo
