### ISSUE TITLE
Develop view Employee section

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1155]

**Comment by rahulxb** [comment]
- [ ]  i. fetch data from db
- [ ]         ii. render in the ui with loading state

**Comment by imranhAltersense** [comment]
1.create employee (frontend + backend)
    2. view employee (frontend + backend)
    3. create designation (frontend + backend)
    4. view designation (frontend + backend)
    5. Session with rafiq vai
        --> create floor 
        --> view floor 
        --> edit floo

**Comment by imranhAltersense** [comment]
1.create employee (frontend + backend)
    2. view employee (frontend + backend)
    3. create designation (frontend + backend)
    4. view designation (frontend + backend)
    5. Session with rafiq vai
        --> create floor 
        --> view floor 
        --> edit floo
