### ISSUE TITLE
creating unique user in the db depending on user input and throw  error if exist [employee]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#1197]

**Comment by imranhAltersense** [comment]
completed

**Comment by imranhAltersense** [comment]
1. created necessary methods in the server
    2. added debounce functionality in (375 ms) to restrict api calling on each input field change
    3. buttons disabled conditionally based on user exist
    4. created a callback function for only clearing input fields after successfully completion of creating employee, else inputs will not be cleared
    5. displayed error in the ui(user already exist!!)
    6. conditionally rendering the the outline border (red in error case)
