### ISSUE TITLE
Performance evaluation [FA] #143 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#213]

**Comment by MunPotter** [comment]
1 hour

**Comment by rahulxb** [comment]
- [ ] - based on training
- [ ] - based on testing

**Comment by MunPotter** [comment]
[](url)![chart_yolo-obj.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/d092500f-e8d1-4203-ba2b-a986a55ceb21)
![Screenshot_1.jpg](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/fa2f4757-6b34-4b1d-b06f-be1a8e3abb70)
