### ISSUE TITLE
Model selection [WC] #143 07/03/22

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#218]

**Comment by smah77** [comment]
Half-day (4H)

**Comment by sanaullah-ashfat** [comment]
Worker count version 1 & 2 ready

**Comment by smah77** [comment]
https://docs.google.com/document/d/1C3VlpXLSzFpgqPeYzzkdD_BiGbNYM7Y-_W3ebNy-gTM/edit?usp=sharing

**Comment by smah77** [comment]
Doc updated
