### ISSUE TITLE
Data annotation #141 09/03/22

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#223]

**Comment by MunPotter** [comment]
Faysal and time: 1 to 2 days

**Comment by rahulxb** [comment]
FA:
- drinking
- talking
- Mobile usage
Allowed activity

**Comment by MunPotter** [comment]
total extracted image: 6000
annotation:
mun:144
faysal:40
hriday:30

**Comment by MunPotter** [comment]
9/3/22
mun:120+50+236
faysal:114+208

**Comment by MunPotter** [comment]
total annotation is done.

location: harddrive ->MUN->all_data_mun->b2bfa_data
