### ISSUE TITLE
Model testing for ANPR 1.1 06/03/22 - 08/03/22

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#224]
06/03/22 - 08/03/22

**Comment by MunPotter** [comment]
continuous checking of RTSP feed for 3-4 days for extreme test cases

**Comment by rahulxb** [comment]
.7/3/2022
Meeting
Character data validation
Character data process for collection
Character data collection (send to Sabbir Bhai for data increment)
Checking ANPR V1 for different RTSP video
Problem: long distance from the camera, vehicle entry from the wrong angle, blur issue, high speed during vehicle exit.

**Comment by MunPotter** [comment]
Checking ANPR V1 only one video for today
