### ISSUE TITLE
ANPR data training for Dhaka metro

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#310]

**Comment by MunPotter** [comment]
![output.jpg](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/ed6c967b-c216-40b1-9fd9-b7ebbda11297)![download.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/a5c0dc05-1199-4a78-9063-fb621d0041ef)

**Comment by MunPotter** [comment]
![download (1).png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/bb1f73ec-b9b5-4303-819f-21e7e0d72202)
