### ISSUE TITLE
Write test script

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#332]

**Comment by rahulxb** [comment]
Should be done by 24/04/22

**Comment by MunPotter** [comment]
![Screenshot_3.jpg](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/bae8378f-292e-4070-bd3a-fa75a1c87f4c)![Screenshot_2.jpg](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/3d1608c8-9d84-4aea-8f95-d37941174f06)
