### ISSUE TITLE
Collect report on pre-trained model testing from Moon

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#342]

**Comment by MunPotter** [comment]
[Uploading... detections.csv]

**Comment by MunPotter** [comment]
https://drive.google.com/drive/folders/1v45yzeLfUvXpcqiR_poKAPKKBXxW2qz4?usp=sharing

visual matrix csv file

**Comment by MunPotter** [comment]
https://docs.google.com/spreadsheets/d/1pK2EIWkR2B6WnuLJjdrQ2kJYzPPcBwf0X07Eaqv3VN4/edit?usp=sharing

confusion matrix file for 660 images
