### ISSUE TITLE
Lofi of #354,355,356

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#360]

**Comment by rahulxb** [comment]
https://www.figma.com/proto/3sqakcsyFtzhSoXVCYIpYv/HeliosG-Lamia?page-id=739%3A14704&node-id=875%3A17988&viewport=304%2C48%2C0.08&scaling=min-zoom

**Comment by lamiajoyee** [comment]
1. Create Information Architecture
2. Create Journey Map
3. Create LoFi UI

**Comment by lamiajoyee** [comment]
1.  Information architecture done
2. Journey map done
3. LoFi done for creating factory, adding departments, import profile, create floors
4. Remaining LoFi: create holidays, create lines, employee profile
