### ISSUE TITLE
Darknet model training

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#365]

**Comment by MunPotter** [comment]
1.data training using 1400 data
2.data training using updated cfg file using 1400 data
3.data training using old data(our annotation method)

**Comment by MunPotter** [comment]
![chart_yolo-obj-updated-3l.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/9c2b359a-24a0-4895-940a-0cd0f4a9f1fc)![3l.PNG](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/e51340cf-4772-499b-86c1-7ba4afff1db0)

task 2 result
