### ISSUE TITLE
Open pose unwrapping [wed-thur]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#368]

**Comment by rahulxb** [comment]
@smah77  please mention the estimated timing required for this along with start date and end date

**Comment by smah77** [comment]
11.05.22:  the whole day will be gone for building the model
12.05.22: With Faisal, unwrapping will be started. Estimated time unknown. May take 2/3 days

**Comment by smah77** [comment]
update: facing dependency issue. Building going on.
Debugging will be started after that.

**Comment by smah77** [comment]
According to Nabeel Sir's direction, stopped working on OpenPose and experimented on the ![DEnsePose.jpeg](https://images.zenhubusercontent.com/62163d5aeebd101f473691c4/88876f3f-3848-4ceb-9db2-0ff7aa288942)code of DensePose at colab
:https://colab.research.google.com/drive/1iKtl2hitn9F8cKwHHOTKSZFJ7jd5tdjI?usp=sharing

**Comment by smah77** [comment]
Densepose is part of FB mega project Detecrton2. The build was successful but laptop memory/GPU was not enough to run the heavy model. 

https://github.com/facebookresearch/detectron2
