### ISSUE TITLE
Logic implementation for open pose

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#370]

**Comment by MunPotter** [comment]
estimated time: N/A

start date:12/5/22
end date: N/A

**Comment by MunPotter** [comment]
need pose logic to define for data extraction pipeline by @rahulxb

**Comment by rahulxb** [comment]
Logics provided by CTO:
- proximity between 2 hands
- hand to working area proximity
- hand to head proximity
- active hands

**Comment by rahulxb** [comment]
hand to head proximity has been primarily tested in sprint 12
