### ISSUE TITLE
Strategy & plan for image manipulation & actor-led data

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#372]

**Comment by smah77** [comment]
Need to fix a meeting with COO, CBO for finalizing the strategy and expected time

**Comment by smah77** [comment]
Image Manipulation: Discussed this with our COO and graphics designer. It will need huge time to manipulate the images and accuracy will be compromised. Not feasible.

The Actor-led Method: This step will be taken under consideration after observing a minimum of 1-week videos of INCTL.
