### ISSUE TITLE
Evaluation report of Darknet [wednesday]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#374]

**Comment by MunPotter** [comment]
![3l.PNG](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/dd9adac6-6e1e-49f7-a1fd-7ae4ebfbbd95)

updated cfg confusion matrix

**Comment by MunPotter** [comment]
https://docs.google.com/spreadsheets/d/1pK2EIWkR2B6WnuLJjdrQ2kJYzPPcBwf0X07Eaqv3VN4/edit#gid=995428797

confusion matrix result

**Comment by MunPotter** [comment]
![chart_yolov4-tiny-custom-3l.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/8c0be622-f88d-459f-8026-0d864f04643f)![Capture.PNG](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/6640cf33-707d-4e5e-9538-ac33214b21fd)


tiny model result (same accuracy as yolov4 and 2 faster than yolov4)
