### ISSUE TITLE
Evaluation report of Retinanet [wednesday]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#375]

**Comment by rahulxb** [comment]
Will rcv 5 reports on 5 backbone models.

**Comment by sanaullah-ashfat** [comment]
retina net : Backbone model resnet 50 result:
Epoch 9: saving model to snapshots/resnet50_csv_09.h5
400/400 [==============================] - 1983s 5s/step - loss: 1.2586 - regression_loss: 1.1053 - classification_loss: 0.1534 - mAP: 0.7887 - lr: 1.0000e-05

**Comment by sanaullah-ashfat** [comment]
retinanet : 
Epoch 13: saving model to snapshots/resnet50_csv_13.h5
400/400 [==============================] - 1983s 5s/step - loss: 1.3586 - regression_loss: .9979 - classification_loss: 0.1356 - mAP: 0.7945 - lr: 1.0000e-05

**Comment by sanaullah-ashfat** [comment]
Model loss study was done but more R&D is needed to tune the model

**Comment by sanaullah-ashfat** [comment]
Fine-tune will be done today and the model will test today on real-time RTSP feed
