### ISSUE TITLE
Experiment for activity detection pipeline

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#403]

**Comment by MunPotter** [comment]
23/5/2022
Data collection and annotation for machine and human(mun)
meeting
Machine and human proximity  script ready (mun, Sana)
Training data process (mun)
Training (mun)
Crop data annotation(andalib)


24/5/2022
Training cropped data(mun)
23/5/22 model pipeline inference (mun, Sana)
meeting
Worker count backend connection (software task)(Sana, Faysal)
GPU memory utilization (task)(Sana)
25/5/2022
Test cropped model(mun)
Detection pipeline code implementation(mun)
Nose and left ear angle and distance calculation(Sana and Faysal)
Worker count code recheck (Sana)
26/5/2022
Two pipelines (person, machine, and person, activity) model tests with code structure(mun)
Machine and face angle, distance calculation(mun,Sana,faysal)
Test machine and face pipeline both video and image(mun, Faysal)
Test all pipelines (mun, Sana, Faysal)

**Comment by MunPotter** [comment]
24/5/2022
Training cropped data(mun)
23/5/22 model pipeline inference (mun, Sana)
meeting
Worker count backend connection (software task)(Sana,Faysal)
GPU memory utilization (task)(sana)

**Comment by MunPotter** [comment]
25/5/2022
Test cropped model(mun)
Detection pipeline code implementation(mun)
Nose and left ear angle and distance calculation(Sana and Faysal)
Worker count code recheck (Sana)

**Comment by MunPotter** [comment]
26/5/2022
Two pipelines (person, machine, and person, activity) model tests with code structure(mun)
Machine and face angle, distance calculation(mun,Sana,faysal)
Test machine and face pipeline both video and image(mun, Faysal)
Test all pipelines (mun, Sana, Faysal)
