### ISSUE TITLE
Feedbacks on Employee management #355

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#409]

**Comment by rahulxb** [comment]
- Individual profile import during employee setup
- Switch the role assignment feature to the settings
- Line wise role assignment from employee creation or profile using filtration.

**Comment by lamiajoyee** [comment]
Estimated time: 3 hrs 

- Individual profile import <0.25 hrs 
- Switch the role assignment to the settings 2 hrs (0.5hrs planning, 1.5 hrs execution)
- Line wise role assignment 1 hr (0.25 hrs planning, rest execution)

**Comment by lamiajoyee** [comment]
Done
