### ISSUE TITLE
Hifi of 1.1-1.3

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#413]

**Comment by lamiajoyee** [comment]
List of tasks:

1. Component & Style creation

- [ ] Headers (0.5 hr)

- [ ] Navigation (minimal)

- [ ] Dropdown (0.5 hrs)

- [ ] Left Panel (minimal)

- [ ] Buttons (0.5 hrs)

- [ ] Tabs (0.5 hrs)

- [ ] Button List (minimal)

- [ ] Bar chart (1.5 hr)

- [ ] Line chart (1 hrs)

- [ ] Stacked bar chart (0.5 hr)

- [ ] Progress chart (0.5 hr)

- [ ] Pie chart (1 hr)

- [ ] Scattered plot chart (1.25 hr)

- [ ] Card view (0.5 hr)

- [ ] Table view (2 hrs)

- [ ] See details (minimal)

2. Place the components in the UI 

- [ ] Home (2 hrs)

- [ ] Attendance details (3 hrs)

- [ ] Worker count details (1.5 hrs)

- [ ] System loss details (1 hr)

**Comment by lamiajoyee** [comment]
(Jun7 12:00pm onwards) Service disruption in Figma is greatly hampering normal work speed.
