### ISSUE TITLE
Helios G lite version 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#416]

**Comment by lamiajoyee** [comment]
Brainstorming (1hr)
Sketching (2hrs)
Implementation (3hrs)

**Comment by lamiajoyee** [comment]
Done

**Comment by rahulxb** [comment]
Please ensure the thresholding of each floor can be set from master module
![image.png](https://images.zenhubusercontent.com/61f6be9005ffa9e845e0af5a/33d849a6-f5cd-48a2-bc0f-1926e668ced1)
