### ISSUE TITLE
Design UML class diagram for 1.3 [30/05]

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#418]

**Comment by tazaki63** [comment]
designs are not being populated

**Comment by tonmoyfarhad** [comment]
For 1.3 instead of only UML we have made detail mongo collections design, trigger sudo code system design. I also give it in the discord

**Comment by tazaki63** [comment]
provide the docs/link to the docs here. discord is for general communication. this is our main activity board

**Comment by tazaki63** [comment]
provide the docs/link to the docs here. discord is for general communication. this is our main activity board

**Comment by tonmoyfarhad** [comment]
[https://app.zenhub.com/files/460831955/e4666005-9904-41dd-be2f-71f39d3469e0/download](https://app.zenhub.com/files/460831955/e4666005-9904-41dd-be2f-71f39d3469e0/download)

**Comment by tazaki63** [comment]
perfect. thanks farhad!

**Comment by tazaki63** [comment]
i just went over the document...this looks like mongo db stuff. i saw no uml inside for 1.3
