### ISSUE TITLE
 Present, Absent Pipeline Test & Evaluation

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#449]

**Comment by MunPotter** [comment]
unique truth:
total frame - 318 images
total-image-1908 images
total absent-169 images
total multi-person-278 images


model result:
absent:
1.  true:163
2. false:119

multi-person:
1. true: 231
2. false:30

sew:
1. true:86
2. false:40

get_put:
1. true:347
2. false:7

other: 804 images
