### ISSUE TITLE
 Activity Analysis with Pipeline

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#451]

**Comment by rahulxb** [comment]
Plus Shohan

**Comment by MunPotter** [comment]
![frame_1_box3.jpg](https://ima![frame_0_box3.jpg](https://ima![frame_3_box2.jpg](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/c509594d-fd01-485f-af91-284e87c61b74)ges.zenhubusercontent.com/6214fc9c81012a3d3053ec25/8e98066a-3d07-40dd-9d0c-b007290f4a36)ges.zenhubusercontent.com/6214fc9c81012a3d3053ec25/21a30692-ff6b-497b-b41f-23fed63a4fab)

**Comment by MunPotter** [comment]
analysis part 1 complete
