### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#471]

**Comment by niyazed** [comment]
# For local and remote dump and restore:
## For Local

### Local dump:

`mongodump -d mydb -o ./mongo-backup`

### Local restore:

`mongorestore -d mydb ./mongo-backup/mydb`

## For remote

### Remote dump

`mongodump --uri "mongodb+srv://Admin:MYPASS@appcluster.15lf4.mongodb.net/mytestdb" -o ./mongo-backup`

### Remote restore

`mongorestore --uri "mongodb+srv://Admin:MYPASS@appcluster.15lf4.mongodb.net/mytestdb" ./mongo-backup/mytestdb`
