### ISSUE TITLE
Functionalities of Dropdowns

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#500]

**Comment by rahulxb** [comment]
- [ ] 1. Attendance Details--> Datepicker, Floor, Section, Sewing (more), Sorting, Absent | Late | Leave, Pagination
- [ ] 2. Worker Count Details--> Datepicker, Floor

**Comment by lamiajoyee** [comment]
Meeting and supervision of Deshal website. 3.5 hours
