### ISSUE TITLE
1.1 initial skeleton making

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#502]

**Comment by tazaki63** [comment]
where is the skeleton? remove the invisibility cloak

**Comment by tonmoyfarhad** [comment]
Skeleton means html structure of worker count initial page(1.1). There are 2 things first make the html structure and then make it functional. Here is the outcome of skeleton. I rather say skeleton with flesh :p 
![Untitled.png](https://images.zenhubusercontent.com/62494a411443542174778e03/0c3d8d5e-d970-4b78-9abb-56682a6df922)
