### ISSUE TITLE
Master data view

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#528]

**Comment by rahulxb** [comment]
- [ ] 1. Factory View
- [ ] 2. Holiday View
- [ ] 3. Floor View
- [ ] 4. Employee View
- [ ] 5. Camera View
- [ ] 6. Machine View
- [ ] 7. Role assignment

**Comment by lamiajoyee** [comment]
- [ ] 1. Factory View

 

- [ ] 2. Holiday View

- [ ]  3. Floor View

- [ ]  4. Employee View

 

- [ ] 5. Camera View

- [ ]  6. Machine View

- [ ]  7. Role assignment
