### ISSUE TITLE
Knowledge sharing & make Sabbir vai actively involve with frontend

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#554]

**Comment by tazaki63** [comment]
add details to use cases that have vague titles. for this one, I know what is happening, but I don't know the depth and breadth of what is happening
tools, plans etc nothing mentioned

**Comment by tonmoyfarhad** [comment]
- Environment  Set up 
- Let Sabbir Vai know what code has been written so far, codding practice, version management, 
- And finally where to put his code in the code base for the date picker
