### ISSUE TITLE
Yolo activity data check from acme ai using makesense day 1

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#570]
17/7/22

**Comment by rahulxb** [comment]
plus shohan

**Comment by tazaki63** [comment]
when this gets done write a comment giving the statistics of your findings

**Comment by Moshiur-Rahman-Faisal** [comment]
Get_Put Data: 4875
Sewing Data: 4571

Had to reshape the bounding box (fix annotation) after getting the annotated data from Acme AI
