### ISSUE TITLE
1.1.3 Performace Analysis Trigger R&D, Collection Design

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#612]

**Comment by codewithrafiq** [comment]
# Collection Design

## floor1_performance_analysis
{
	date:{
		year:2022,
		month:7,
		day:25
	},
	top_performing:{
		line:int,
		tam: int,
		npt: int,
		percentage: int%,
	},
	bottom_performing:{
		line: int,
		tam: int,
		npt: int,
		percentage: int%,
	}
}


## floor2_performance_analysis
{
	date:{
		year:2022,
		month:7,
		day:25
	},
	top_performing:{
		line:int,
		tam: int,
		npt: int,
		percentage: int%,
	},
	bottom_performing:{
		line: int,
		tam: int,
		npt: int,
		percentage: int%,
	}
}



## all_floor_performance_analysis
{
	date:{
		year:2022,
		month:7,
		day:25
	},
	top_performing:{
		line:int,
		tam: int,
		npt: int,
		percentage: int%,
	},
	bottom_performing:{
		line: int,
		tam: int,
		npt: int,
		percentage: int%,
	}
}
