### ISSUE TITLE
 Backend code optimization

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#872]

**Comment by rafiqul-altersense** [comment]
https://github.com/Altersense-PM/Helios-software-v1/tree/dev_rafiqul

**Comment by Fayeeza-altersense** [comment]
Backcode was reviewed and optimized 
https://docs.google.com/document/d/12vR9ZWNbCw0fl7fhYXa9MHYj4NUEn3_gWMCIggVnNNo/edit?usp=sharing

**Comment by codewithrafiq** [comment]
### Backend optimize codes
- https://github.com/Altersense-PM/Helios-software-v1/tree/dev_rafiqul
