### ISSUE TITLE
Demo Project

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#899]

**Comment by rahulxb** [comment]
- [ ]  - Create Collections to make an authentication system.
- [ ]     - Required Packages.
- [ ]     - Login.
- [ ]     - Register.
- [ ]     - Role-based authentication.
- [ ]     - Role-based authorization.

**Comment by imranhAltersense** [comment]
1. Added mongodb and created related collections
    2. Added register and login functionality
    3. Added role based authentication
        --> only loggedin user will be able to login
    4. Added  role based authorization 
        --> logged in user can set role and permissions
        --> only admin role can delete other users
        --> logged in user can add todo
        --> only todos created by logged in user will be able to see his todos
