### ISSUE TITLE
Authentication System Design for the real project

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#900]

**Comment by rahulxb** [comment]
- [ ]  - Login Register functionality.
- [ ]     - Role-based authentication and authorization functionality

**Comment by imranhAltersense** [comment]
created a design model combining below things:
        1. separate modules for master module and helios dashboard
        2. extracted collections about possible db collection regarding the master module
        3. separate login for both master and helios dashboard
        4. Same Mongodb will be used for both of the modules
        5. Meteor will be used for authentication system along with meteor accounts package
