### ISSUE TITLE
Master mod updates

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#913]

**Comment by rahulxb** [comment]
- [ ] 1. Master Module-> Role Based-> Add "All" and "Permissions" in module selection dropdown: 15 mins
- [ ] 2. Master Module-> Role Based-> Add Reset Password option in All User Profiles: 30 mins
- [ ] 3. Master Module-> Role Based-> Add "My Profile" in top bar: 30 mins
- [ ] 4. Master Module-> Schedule-> Add option to select weekend from seven days in a week: 30 mins

**Comment by lamiajoyee** [comment]
- [ ] 1. Master Module-> Role Based-> Add "All" and "Permissions" in module selection dropdown: 15 mins

 

- [ ] 2. Master Module-> Role Based-> Add Reset Password option in All User Profiles: 30 mins

 

- [ ] 3. Master Module-> Role Based-> Add "My Profile" in top bar: 30 mins

 

- [ ] 4. Master Module-> Schedule-> Add option to select weekend from seven days in a week: 30 mins
