### ISSUE TITLE
Gotipath testing

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#924]

**Comment by MunPotter** [comment]
![goti.png](https://images.zenhubusercontent.com/6214fc9c81012a3d3053ec25/945404a8-2056-46bf-b6a7-c2ef44261c89)


video send to Mohan Bhai

**Comment by MunPotter** [comment]
https://drive.google.com/drive/folders/1M4sDRQfp4Vbe1PFuwghZ9QWz0qKRosCx?usp=sharing
