### ISSUE TITLE
Creating master module environment

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#948]

**Comment by rahulxb** [comment]
--> Create a github repo
        --> Install meteor, svelte and Tailwind
        --> Folder structure
        --> connect Mongodb

**Comment by imranhAltersense** [comment]
creating master module environment
        1. installed meteor, svelte and meteor
        2. connected to gituhub
        3. created folder structure for the project
        4. added routing
        5. created layouts for the routes
        6. Refactored and optimized the sidebar component
        7. added login page, Refactored and optimized Login page design
