### ISSUE TITLE
Design user authentication and user creation page interface

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#949]

**Comment by rahulxb** [comment]
- [ ]    1. create new role (5 hours)
- [ ]         2. create new user (5 hours)
- [ ]         3. users list (5 hours)
- [ ]         4 .roles list (5 hours)

**Comment by imranhAltersense** [comment]
User UI design
        --> User and roles info section
        --> Add user section
        --> Add role section
        --> Create user
        --> Create role
        --> User list 
        --> Role list
