### ISSUE TITLE
Responsive design for create camera profile pages 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#951]

**Comment by codewithrafiq** [comment]
- Design Create Camera Profile Page
  - Layout Design
  - Back Button for go camera page
  - From Design
    - Text input field 
    - Select the option input field. 
  - Add some Common Colors on the tailwind config file

![create-camera.png](https://images.zenhubusercontent.com/6215b5557b25bb86065df891/aec7c5c0-9c85-4050-bcd2-dd1d046c04f0)
