### ISSUE TITLE
 Role create

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#983]

**Comment by rahulxb** [comment]
- [ ]     --> check required fields
- [ ]     --> save to database

**Comment by imranhAltersense** [comment]
1. Role create: 8 hours
            --> validation on required fields 
            --> enable or disable submit button based input fields
            --> disabled insecure package from meteor
            --> disabled auto-publish package from meteor
            --> created mongodb instance and necessary collection
            --> created a method "roles.findRole" in meteor server to check if user already exist
            --> used the method and based on the response, we are alerting user if it's already exist
            --> created another method "roles.create" in meteor server to insert roles data into the database
            --> checked the type of incoming parameteres in "roles.create" method
            --> if the role is not exist used the "roles.create" method to insert the roles data into the database
            --> based ont the method response, we are alerting our user whether the role data is inserted or not
