### ISSUE TITLE
Role List 

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#984]

**Comment by rahulxb** [comment]
- [ ]     --> Fetch roles from database
- [ ]     --> Display in the UI

**Comment by imranhAltersense** [comment]
1. Fetch roles: 4 hours
                --> created role publisher
                --> consumed data from publisher with subscriber
                --> resoloved $m tracker issue
                        --> removed rdb:svelte-meteor-data package which was causing problem
                        --> monitored meteor developer tools to find the issue
                --> fetched all roles from meteor with $m tracker

            2. Display in the UI: 4 hours
                --> conditional rendering based on the rolelist is empty or not
                --> created a helper function "getTabsData" to get the tabs data from the rolelist
                --> conditional rendering when the tabsdata are avaialble(initially loading)
                --> dynamic tabs based on the tabs data
                --> dynamic tabs content corresponding tabs
