### ISSUE TITLE
 User List

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#986]

**Comment by rahulxb** [comment]
- [ ]   --> Fetch users from database
- [ ]    --> display user in the Ui

**Comment by imranhAltersense** [comment]
1. Fetch users
                --> created users publisher
                --> consumed data from publisher with subscriber
                --> fetched all users from meteor with $m tracker
            2. Display in the UI: 
                --> conditional rendering based on the userList is empty or not
                --> based on userlist displaying data in the ui
