### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#987]

**Comment by rahulxb** [comment]
- [ ]   --> user fetch
- [ ]   --> credentials match
- [ ]   --> redirect to master module

**Comment by imranhAltersense** [comment]
--> Having issue with login(error: user not found, need to be resolved)
--> we have Meteor community issues and svelte as well

**Comment by imranhAltersense** [comment]
1. Previous days issue resolve 
            -->  took help from meteor documentaion how the process is working
            -->  user not found issue has been resolved
                          1. using Accounts.createUser() method in the server side to avoid logging in while creating a user
                          2. along with email and password, providing other data to create user as profile object
        2. user fetch and credentials match
            --> using Meteor.loginWithPassword() method in the client side to login the user
            --> Added loading state while submittig the credentials 
            --> if credential doesn't match providing error messages as alert
                    --> error messages(email not found, password inccorect)
        3. redirect to master module
            --> if user provides correct credential, we are keeping tract of the users curernt loggedIn status using $m tracker
            --> if user loggedIn, we are redirecting to the dashboard
        4. Logout Functionality
            --> added user data(name) in the ui using current loggedIn users credentials
            --> while clicking logout button, the Meteor.logout() method is invoked
            --> Added loading state
            --> provided error message if logout failed as alert
            --> for successfull logout it will redirected to login page
        5. Team discussion on system architecture, system design and schema design
