### ISSUE TITLE
Employee Page Design(2 pages)

### ISSUE THREAD

**Issue by rahulxb** [Altersense-PM/Team-PM#996]

**Comment by codewithrafiq** [comment]
# Done below things in this commit:
  - Added an employee button on the sidebar
  - Employee Profile
    - Layout designed for employee information page
    - Employee profile header section design
    - Employee search box design
    - Employee table for showing employee list
    - Generate employee demo data and showing on the employee table
  - Designations
    - Designation header section design
    - Designation search box design
    - Designation table for showing all designations and the count
    - Generate designations demo data and showing on the designations table.
![Employee Page Design.png](https://images.zenhubusercontent.com/6215b5557b25bb86065df891/216008d5-1fec-452c-90c0-c3f43778ee95)
